version: '3.8'

services:
  tomcat:
    container_name: tomcat
    image: tomcat:9.0.80-jre11
    volumes:
      - ./SQLInfo/target/sqlinfo.war:/usr/local/tomcat/webapps/sqlinfo.war
    depends_on:
      - db
    links:
      - db


  db:
    container_name: db
    environment:
      - POSTGRES_DB=sqlinfo_t
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    image: postgres:latest
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d


  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - tomcat
    links:
      - tomcat
